test
streamnative/pulsar-io-aws-eventbridge pull request #69
Opened 2023-07-27 09:47 UTC by shibd

2023-07-27 11:02 UTC, shibd commented on docs/aws-eventbridge-sink-new.md
> +## 1. Create Connector
When the user comes to this step,Needs to be carried out in conjunction with the reading `sn cloud`, `function mesh`, `pulsar function worker` docs.

2023-08-01 03:18 UTC, momo-jun commented
@shibd, thanks for the initiative to restructure the docs.

I have the following suggestions for the proposed structure in general:
1. Make "Prerequisites" relevant to an action (user task) to provide more context, for example, the Quick Start for setting up the connector. Does it make sense to move "Prerequisites" under "Quick Start"?
2. No need to amplify "limitations". The two items you listed here are actually the deployment requirement and supportability, IMO. We can eliminate the heading "limitations" and attach the bullets to where it applies.

2023-08-01 06:08 UTC, poorbarcode approved these changes

2023-08-01 06:58 UTC, momo-jun commented on docs/aws-eventbridge-sink-new.md
> +- [Create Connector with StreamNative Cloud](https://main.sn-docs.pages.dev/docs/connector-pulsarctl).
```suggestion
- [Create Connector on StreamNative Cloud](https://docs.streamnative.io/docs/connector-create).
```

You can use the link for the new doc.

2023-08-01 07:03 UTC, momo-jun commented on docs/aws-eventbridge-sink-new.md
> +> If your connector is created on StreamNative Cloud, please refer to this [document](TODO) on how to authenticate clients.
Does this imply that users can skip this step if the connector is created with Function worker/mesh?

2023-08-01 09:03 UTC, shibd commented on docs/aws-eventbridge-sink-new.md
> +> If your connector is created on StreamNative Cloud, please refer to this [document](TODO) on how to authenticate clients.
No, Using the client on SN cloud requires some additional authentication configuration, and this is just a reminder to the user.

2023-08-01 09:40 UTC, shibd commented
> Make "Prerequisites" relevant to an action (user task) to provide more context, for example, the Quick Start for setting up the connector. Does it make sense to move "Prerequisites" under "Quick Start"?

No, If the user does not do `Prerequisites`, they cannot "Quick Start".


> No need to amplify "limitations". The two items you listed here are actually the deployment requirement and supportability, IMO. We can eliminate the heading "limitations" and attach the bullets to where it applies as notes.

Make sense, I removed it.

2023-08-01 10:43 UTC, shibd commented
> @shibd By nesting "Prerequisites" under "Quick Start"`, we can make it part of quickstart in a more cohesive way. They are the prerequisites of creating a connector, like any other sections in parallel.

I see. Make sense to me. Thanks explain.

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +> For advanced features and configuration of this connector, please refer to the Advanced feature for more information.
```suggestion
> For details about this connector's advanced features and configurations, see [Advanced features](#advanced-features).
```

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +## Advanced feature
```suggestion
## Advanced features
```

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +## More Link
```suggestion
## More links
```

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +- Other Configuration
```suggestion
- Other configurations
```

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +This connector provider two authentication methods for AWS EventBridge, please select either authentication method from `Access keys` and `Security Token Service`.
```suggestion
This connector provides two authentication methods for AWS EventBridge. You can select either one between `Access keys` and `Security Token Service`.
```

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +> If your connector is created on StreamNative Cloud, please refer to this [document](TODO) on how to authenticate clients.
```suggestion
> **Note:** If your connector is created on StreamNative Cloud, you need to authenticate your clients. See [Build applications using Pulsar clients](https://docs.streamnative.io/docs/qs-connect#jumpstart-for-beginners) for more information.
```

2023-08-01 11:57 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +### 2. Send message to topic
```suggestion
### 2. Send messages to the topic
```

2023-08-01 11:59 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +> * The above different creation methods are different for the structure of the configuration,
```suggestion
> * The configuration structure varies depending on how you create the AWS EventBridge sink connector.
```

2023-08-01 11:59 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +>  some are **json**, some are **yaml**, some are **k8s yaml**, you only need to replace with the corresponding format.
```suggestion
>  For example, some are **JSON**, some are **YAML**, and some are **Kubernetes YAML**. You need to adapt the configs to the corresponding format.
```

2023-08-01 12:00 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +Each creation way is similar, you just need to set the following parameters to the connector configuration.
```suggestion
No matter how you create an AWS EventBridge sink connector, the minimum configuration contains the following parameters.
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +Please go to the corresponding document for details.
We can remove this sentence. It's explicit.

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +  This way need set docker image. You can choose the version you want to launch from [here](https://hub.docker.com/r/streamnative/pulsar-io-aws-eventbridge/tags)
```suggestion
  Using this way requires you to set the docker image. You can choose the version you want to launch from [here](https://hub.docker.com/r/streamnative/pulsar-io-aws-eventbridge/tags)
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +  This way need download **nar** package to create build-in or no-build-in connector. You can download the version you need from [here](https://github.com/streamnative/pulsar-io-aws-eventbridge/relea
```suggestion
  Using this way requires you to download a **NAR** package to create a built-in or non-built-in connector. You can download the version you need from [here](https://github.com/streamnative/pulsar-io-aws-eventbridge/releases).
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +To create AWS EventBridge sink connector, depending on the environment, there are several ways to create it:
```suggestion
Depending on the environment, there are several ways to create an AWS EventBridge sink connector:
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +### 1. Create Connector
```suggestion
### 1. Create a connector
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +- Set the target according to your needs. If you're testing this connector, you can set target to [Cloud Watch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html)
```suggestion
- Set the target according to your needs. If you're testing this connector, you can set the target to [Cloud Watch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html).
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +- [Security Token Service](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html): If you use this method, Just need set `stsEndpoint`, `stsRegion`, `role`, and `roleSessionName` on this c
```suggestion
- [Security Token Service](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html): To use this method, you need to set `stsEndpoint`, `stsRegion`, `role`, and `roleSessionName` on this connector config.
```

2023-08-01 12:01 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +- [Access Keys](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-appendix-sign-up.html): If you use this method, Just need set `accessKeyId` and `secretAccessKey` on this connector con
```suggestion
- [Access Keys](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-appendix-sign-up.html): To use this method, you need to set `accessKeyId` and `secretAccessKey` on this connector config.
```

2023-08-01 12:03 UTC, momo-jun requested changes
Added a few suggestions to fix obvious typos and align the common writing style.

2023-08-02 12:19 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +2. Create the [AWS User](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html) and create `Access Key`(Please record `accessKey` and `secretAccessKey`).
Any difference between `Access Key` and `accessKey`? Does it make sense to get them aligned?

2023-08-02 12:19 UTC, momo-jun commented on docs/aws-eventbridge-sink.md
> +3. Set permissions to users, ensure that the user has the following permissions to the AWS EventBus. For details, see [permissions for event buses](https://docs.aws.amazon.com/eventbridge/latest/user
```suggestion
3. Assign permissions to Pulsar users, and ensure they have the following permissions to the AWS EventBus. For details, see [permissions for event buses](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus-perms.html)
```

2023-08-03 02:15 UTC, RobertIndie approved these changes

2023-08-03 10:02 UTC, merged